describe("fn.combined", function()
  local t, combined, to
  setup(function()
    t = require "meta"
    combined = t.fn.combined
    to = t.to
  end)
  it("tostring + tonumber", function()
    local f = combined(tostring, to.number)
    assert.equal(777, f(777))
    assert.equal(777, f('777'))
  end)
  it("tostring + string.toupper", function()
    local f = combined(tostring, string.upper)
    assert.equal('NEWTON CLASS', f('newton class'))
    assert.equal('MICRO SOFT', f('micro soft'))
  end)
  it("tonumber", function()
    local f = combined(to.number)
    assert.equal(777, f(777))
    assert.equal(777, f('777'))
  end)
  it("nil", function()
    local f = combined(nil, nil)
    assert.equal('russia', f('russia'))
  end)
end)
