describe("number.natural", function()
  local number, natural
  setup(function()
    require 'meta'
    number = require 'meta.number'
    natural = number.natural
  end)
  it("meta", function()
    assert.callable(natural)
  end)
  it("positive", function()
    for i=1,512 do
      assert.equal(i, natural(i))
    end
    assert.equal(1, natural(true))
    assert.equal(1, natural("1"))
  end)
  it("negative", function()
    assert.is_nil(natural("0"))
    assert.is_nil(natural(false))
    assert.is_nil(natural(math.pi))
    assert.is_nil(natural(-1))
    assert.is_nil(natural(0))
    assert.is_nil(natural(""))
    assert.is_nil(natural(' '))
    assert.is_nil(natural('  '))
    assert.is_nil(natural('	'))
    assert.is_nil(natural('		'))
    assert.is_nil(natural("	\r 	"))
    assert.is_nil(natural("	\n 	"))
    assert.is_nil(natural({}))
    assert.is_nil(natural("false"))
    assert.is_nil(natural("FALSE"))
  end)
  it("nil", function()
    assert.is_nil(natural(nil))
    assert.is_nil(natural())
  end)
end)