describe("number.znegative", function()
  local number, znegative
  setup(function()
    require 'meta'
    number = require 'meta.number'
    znegative = number.znegative
  end)
  it("meta", function()
    assert.callable(znegative)
  end)
  it("positive", function()
    for i=1,512 do
      assert.equal(-i, znegative(-i))
    end
    assert.equal(0, znegative(0))
    assert.equal(-1, znegative(-1))
    assert.equal(0, znegative("0"))
    assert.equal(-1, znegative("-1"))
    assert.equal(0, znegative(false))
  end)
  it("znegative", function()
    assert.is_nil(znegative(true))
    assert.is_nil(znegative(math.pi))
    assert.is_nil(znegative(""))
    assert.is_nil(znegative(' '))
    assert.is_nil(znegative('  '))
    assert.is_nil(znegative('	'))
    assert.is_nil(znegative('		'))
    assert.is_nil(znegative("	\r 	"))
    assert.is_nil(znegative("	\n 	"))
    assert.is_nil(znegative({}))
    assert.is_nil(znegative("false"))
    assert.is_nil(znegative("FALSE"))
  end)
  it("nil", function()
    assert.is_nil(znegative(nil))
    assert.is_nil(znegative())
  end)
end)