describe("string.null", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = meta.is
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(string.null))
  end)
  it("positive", function()
    assert.equal('ok', string.null('ok'))
    assert.equal('some long string', string.null('some long string'))
  end)
  it("negative", function()
    assert.is_nil(string.null(''))
    assert.is_nil(string.null({}))
    assert.is_nil(string.null(0))
    assert.is_nil(string.null(1))
    assert.is_nil(string.null(false))
    assert.is_nil(string.null(true))
  end)
  it("nil", function()
    assert.is_nil(string.null(nil))
    assert.is_nil(string.null())
  end)
end)