describe("is.fs.abspath", function()
	local is, path
	setup(function()
    is = require 'meta.is'
    path = require 'meta.fs.path'
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.fs)
    assert.truthy(is.fs.abspath)
  end)
  it("positive", function()
    assert.is_true(is.fs.abspath('/a'))
    assert.is_true(is.fs.abspath({[0]='','x'}))
    assert.is_true(is.fs.abspath({'/q','x'}))

    assert.is_true(is.fs.abspath(path('/a')))
    assert.is_true(is.fs.abspath(path({[0]='','x'})))
    assert.is_true(is.fs.abspath(path({'/q','x'})))
  end)
  it("negative", function()
    assert.is_nil(is.fs.abspath({}))
    assert.is_nil(is.fs.abspath(1))
    assert.is_nil(is.fs.abspath(true))
    assert.is_nil(is.fs.abspath(''))
    assert.is_nil(is.fs.abspath('a'))
    assert.is_nil(is.fs.abspath(string.lower))
  end)
  it("nil", function()
    assert.is_nil(is.fs.abspath(nil, nil))
    assert.is_nil(is.fs.abspath(nil))
    assert.is_nil(is.fs.abspath())
  end)
end)