describe("is.fs.file", function()
  local meta, is, path
  setup(function()
    meta = require "meta"
    is = meta.is
    path = require 'meta.fs.path'
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable)
    assert.truthy(is.fs)
    assert.truthy(is.callable(is.fs.file))
  end)
  describe("tests", function()
    it("cwd", function()
      assert.is_nil(is.fs.file(''))
      assert.is_nil(is.fs.file('.'))
    end)
    it("dir", function()
      assert.is_nil(is.fs.file(path('testdata').instance))

      assert.is_nil(is.fs.file('testdata'), 'testdata')
      assert.is_nil(is.fs.file('testdata/ok'), 'testdata/ok')
      assert.is_nil(is.fs.file('/'), '/')
      assert.is_nil(is.fs.file('/tmp'), '/tmp')
      assert.is_nil(is.fs.file('/var'), '/var')
      assert.is_nil(is.fs.file('testdata/loader/noinit'), 'testdata/loader/noinit')
      assert.is_nil(is.fs.file('testdata/loader/failed'), 'testdata/loader/failed')
    end)
    it("path", function()
      assert.is_true(is.fs.file(path('testdata/ok/message.lua')))
    end)
    it("io object", function() assert.is_true(is.fs.file(io.stdin)) end)
    it("file", function() assert.is_true(is.fs.file('testdata/test')) end)
    it("file.empty", function() assert.is_true(is.fs.file('testdata/empty')) end)
    it("noneexistent", function() assert.is_nil(is.fs.file('testdata/noneexistent')) end)
    it("dev_zero", function() assert.is_true(is.fs.file('/dev/zero')) end)
    it("dev_zero", function() assert.is_true(is.fs.file('/dev/null')) end)
  end)
end)