describe("is.fs.skip", function()
	local is, path
	setup(function()
    is = require 'meta.is'
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.fs)
    assert.truthy(is.fs.skip)
  end)
  it("positive", function()
    assert.is_true(is.fs.skip(''))
    assert.is_true(is.fs.skip('.'))
    assert.is_true(is.fs.skip('..'))
    assert.is_true(is.fs.skip('...'))
  end)
  it("negative", function()
    assert.is_nil(is.fs.skip({}))
    assert.is_nil(is.fs.skip(1))
    assert.is_nil(is.fs.skip(true))
    assert.is_nil(is.fs.skip('a'))
    assert.is_nil(is.fs.skip(string.lower))
  end)
  it("nil", function()
    assert.is_nil(is.fs.skip(nil, nil))
    assert.is_nil(is.fs.skip(nil))
    assert.is_nil(is.fs.skip())
  end)
end)