describe("match.lua_fileext", function()
  local meta, is, match
  setup(function()
    meta = require "meta"
    is = meta.is
    match = meta.match
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(table))
    assert.truthy(is.callable(match.lua_fileext))
  end)
  it("positive", function()
    assert.equal('.lua', match.lua_fileext('.lua'))
    assert.equal('.any.lua', match.lua_fileext('.any.lua'))
  end)
  it("negative", function()
    assert.is_nil(match.lua_fileext('/init.lua'))
    assert.is_nil(match.lua_fileext(''))
    assert.is_nil(match.lua_fileext(' '))
    assert.is_nil(match.lua_fileext('  '))
    assert.is_nil(match.lua_fileext('   '))
    assert.is_nil(match.lua_fileext('    '))
    assert.is_nil(match.lua_fileext(true))
    assert.is_nil(match.lua_fileext(false))
  end)
  it("nil", function()
    assert.is_nil(match.lua_fileext())
    assert.is_nil(match.lua_fileext(nil))
  end)
end)