describe("match.parent", function()
  local meta, is, match
  setup(function()
    meta = require "meta"
    is = meta.is
    match = meta.mt.match
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(table))
    assert.truthy(is.callable(match.parent))
  end)
  it("positive", function()
    assert.equal('meta/mcache', match.parent('meta/mcache/root.d'))
    assert.equal('meta/mcache', match.parent('meta/mcache/root'))
    assert.equal('meta', match.parent('meta/loader'))
    assert.equal('meta', match.parent('meta/assert.d'))
    assert.equal('meta', match.parent('meta'))
  end)
  it("negative", function()
    assert.is_nil(match.parent(' meta'))
    assert.is_nil(match.parent(''))
    assert.is_nil(match.parent(' '))
    assert.is_nil(match.parent('  '))
    assert.is_nil(match.parent('   '))
    assert.is_nil(match.parent('    '))
    assert.is_nil(match.parent(true))
    assert.is_nil(match.parent(false))
  end)
  it("nil", function()
    assert.is_nil(match.parent())
    assert.is_nil(match.parent(nil))
  end)
end)