describe("match.root", function()
  local meta, is, match
  setup(function()
    meta = require "meta"
    is = meta.is
    match = meta.mt.match
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(table))
    assert.truthy(is.callable(match.root))
  end)
  it("positive", function()
    assert.equal('meta', match.root('meta.loader'))
    assert.equal('meta', match.root('meta/loader'))
    assert.equal('meta', match.root('meta'))
    assert.equal('meta', match.root('meta.to.match  meta.match.t'))
  end)
  it("negative", function()
    assert.is_nil(match.root(' meta'))
    assert.is_nil(match.root(''))
    assert.is_nil(match.root(' '))
    assert.is_nil(match.root('  '))
    assert.is_nil(match.root('   '))
    assert.is_nil(match.root('    '))
    assert.is_nil(match.root(true))
    assert.is_nil(match.root(false))
  end)
  it("nil", function()
    assert.is_nil(match.root())
    assert.is_nil(match.root(nil))
  end)
end)