describe('require', function()
  local is, req
  setup(function()
    is = require "meta.is"
    req = require "meta.mt.require"
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(req))
    assert.is_table(req('meta.mt.require'))
  end)
  it("positive", function()
    local m = req('meta')
    assert.equal(is, m.is)
    assert.equal(is, m('is'))
    assert.is_nil(select(2, req('is')))
  end)
  it("negative", function()
    assert.is_nil(req({}))
    assert.is_nil(req({'type'}))
    assert.is_nil(req(0))
    assert.is_nil(req(''))
    assert.is_nil(req(false))
    assert.is_nil(req(true))

    local m = req('meta')
    assert.is_nil(m())
    assert.is_nil(m(nil))
    assert.is_nil(m(''))

    assert.is_nil(m({}))
    assert.is_nil(m({'type'}))
    assert.is_nil(m(0))
    assert.is_nil(m(false))
    assert.is_nil(m(true))

    assert.equal('meta.mt.require: await prefix (strings), got: not strings or empty', select(2, req('')))
    assert.equal('meta.mt.require: await prefix (strings), got: not strings or empty', select(2, req()))
    assert.equal('meta.mt.require: await prefix (strings), got: not strings or empty', select(2, m('')))
    assert.equal('meta.mt.require: await prefix (strings), got: not strings or empty', select(2, m()))
  end)
  it("nil", function()
    assert.is_nil(req())
    assert.is_nil(req(nil))
    assert.is_nil(req(nil, nil))
  end)
end)