describe("is.number.byte", function()
  local is
  setup(function()
    require 'meta'
    is = require 'meta.is'
  end)
  it("meta", function()
    assert.callable(is.number.byte)
  end)
  it("positive", function()
    for i=0,255 do
      assert.is_true(is.number.byte(i))
    end
  end)
  it("negative", function()
    assert.is_nil(is.number.byte(math.pi))
    assert.is_nil(is.number.byte(-1))
    assert.is_nil(is.number.byte(256))
    assert.is_nil(is.number.byte(""))
    assert.is_nil(is.number.byte(' '))
    assert.is_nil(is.number.byte('  '))
    assert.is_nil(is.number.byte('	'))
    assert.is_nil(is.number.byte('		'))
    assert.is_nil(is.number.byte("	\r 	"))
    assert.is_nil(is.number.byte("	\n 	"))
    assert.is_nil(is.number.byte({}))
    assert.is_nil(is.number.byte("false"))
    assert.is_nil(is.number.byte("FALSE"))
  end)
  it("nil", function()
    assert.is_nil(is.number.byte(nil))
    assert.is_nil(is.number.byte())
  end)
end)