describe("is.number.negative", function()
  local is
  setup(function()
    require 'meta'
    is = require 'meta.is'
  end)
  it("meta", function()
    assert.callable(is.number.negative)
  end)
  it("positive", function()
    for i=1,512 do
      assert.is_true(is.number.negative(-i))
    end
  end)
  it("is.number.negative", function()
    assert.is_nil(is.number.negative(math.pi))
    assert.is_nil(is.number.negative(0))
    assert.is_nil(is.number.negative(1))
    assert.is_nil(is.number.negative(""))
    assert.is_nil(is.number.negative(' '))
    assert.is_nil(is.number.negative('  '))
    assert.is_nil(is.number.negative('	'))
    assert.is_nil(is.number.negative('		'))
    assert.is_nil(is.number.negative("	\r 	"))
    assert.is_nil(is.number.negative("	\n 	"))
    assert.is_nil(is.number.negative(false))
    assert.is_nil(is.number.negative(true))
    assert.is_nil(is.number.negative({}))
    assert.is_nil(is.number.negative("false"))
    assert.is_nil(is.number.negative("0"))
    assert.is_nil(is.number.negative("FALSE"))
  end)
  it("nil", function()
    assert.is_nil(is.number.negative(nil))
    assert.is_nil(is.number.negative())
  end)
end)