describe("is.number.positive", function()
  local is
  setup(function()
    require 'meta'
    is = require 'meta.is'
  end)
  it("meta", function()
    assert.callable(is.number.positive)
  end)
  it("is.number.positive", function()
    for i=1,512 do
      assert.is_true(is.number.positive(i))
    end
  end)
  it("is.number.positive", function()
    assert.is_nil(is.number.positive(true))
    assert.is_nil(is.number.positive(false))
    assert.is_nil(is.number.positive(-math.pi))
    assert.is_nil(is.number.positive(0))
    assert.is_nil(is.number.positive(-1))
    assert.is_nil(is.number.positive(""))
    assert.is_nil(is.number.positive(' '))
    assert.is_nil(is.number.positive('  '))
    assert.is_nil(is.number.positive('	'))
    assert.is_nil(is.number.positive('		'))
    assert.is_nil(is.number.positive("	\r 	"))
    assert.is_nil(is.number.positive("	\n 	"))
    assert.is_nil(is.number.positive({}))
    assert.is_nil(is.number.positive("false"))
    assert.is_nil(is.number.positive("0"))
    assert.is_nil(is.number.positive("FALSE"))
  end)
  it("nil", function()
    assert.is_nil(is.number.positive(nil))
    assert.is_nil(is.number.positive())
  end)
end)