describe("fs.block", function()
  local meta, is, block
  setup(function()
    meta  = require "meta"
    is    = require 'meta.is'
    block = meta.fs.block
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(block))
  end)
  it("positive", function()
    assert.equal(256, block(256))
    assert.equal('*a', block('*a'))
    assert.equal('*a', block('*all'))
    assert.equal('*n', block('*n'))
    assert.equal('*n', block('*num'))
    assert.equal('*n', block('*number'))
    assert.equal('*l', block('*l'))
    assert.equal('*l', block('*line'))
    assert.equal('*l', block('*lines'))
  end)
  it("negative", function()
    assert.is_nil(block(''))
    assert.is_nil(block(false))
    assert.is_nil(block(true))
    assert.is_nil(block({}))
    assert.is_nil(block(string.lower))
  end)
  it("nil", function()
    assert.is_nil(block())
    assert.is_nil(block(nil))
  end)
end)