describe("path", function()
  local is, fs, path, iter, tuple
  setup(function()
    iter = require 'meta.iter'
    is = require 'meta.is'
    fs = require 'meta.fs'
    path = fs.path
    tuple = iter.tuple
  end)
  it("meta", function()
    assert.truthy(is.callable(path))
    assert.equal('testdata/x', tostring(path('testdata/x')))
    assert.equal('/tmp', tostring(path('/tmp')))

    assert.equal(path, fs.path)

    local id = require 'meta.mt.id'
    assert.is_true(is.callable(id))
    assert.equal(id(path('/tmp')), tostring(path('/tmp')))
  end)
  describe("new", function()
    it(".", function()
      assert.equal('', tostring(path('')))
      assert.equal(path(''), path(''))
      assert.equal(path(''), path('.'))
      assert.equal(path(''), path())
      assert.equal(path(''), path({}))
      assert.equal(path(''), path(tuple('')))
      assert.equal(path(''), path(tuple('.')))
      assert.equal(path(''), path(tuple()))
      assert.equal(path(''), path(tuple({})))
      assert.equal(path(''), path(tuple(path(''))))
    end)
    it("1", function()
      assert.equal('testdata', tostring(path('testdata')))
      assert.equal(path('testdata'), path('testdata'))
      assert.equal(path('testdata'), path('./testdata'))
      assert.equal(path('testdata'), path({'testdata'}))

      assert.equal(path('testdata'), path(tuple('testdata')))

      assert.equal(path('testdata'), path(path('testdata')))
      assert.equal(path('testdata'), path(tuple('testdata')))
      assert.equal(path('testdata'), path(tuple('./testdata')))
      assert.equal(path('testdata'), path(tuple({'testdata'})))
      assert.equal(path('testdata'), path(tuple(path('testdata'))))
    end)
    it("2", function()
      assert.equal('testdata/x', tostring(path('testdata/x')))
      assert.equal(path('testdata/x'), path('testdata/x'))
      assert.equal(path('testdata/x'), path('./testdata/x'))
      assert.equal(path('testdata/x'), path({'testdata/x'}))
      assert.equal(path('testdata/x'), path(tuple('testdata/x')))
      assert.equal(path('testdata/x'), path(tuple('./testdata/x')))
      assert.equal(path('testdata/x'), path(tuple({'testdata/x'})))
      assert.equal(path('testdata/x'), path({tuple('testdata/x')}))

      assert.equal(path('testdata/x'), path('testdata', 'x'))
      assert.equal(path('testdata/x'), path({'testdata'}, 'x'))
      assert.equal(path('testdata/x'), path('testdata', {'x'}))
      assert.equal(path('testdata/x'), path({'testdata', 'x'}))

      assert.equal(path('testdata/x'), path(path('testdata'), path('x')))
      assert.equal(path('testdata/x'), path(path('./testdata'), path('x')))
      assert.equal(path('testdata/x'), path(path({'testdata', 'x'})))
      assert.equal(path('testdata/x'), path({path('testdata'), path('x')}))

      assert.equal(path('testdata/x'), path('testdata', tuple('x')))
      assert.equal(path('testdata/x'), path(tuple('testdata'), 'x'))
      assert.equal(path('testdata/x'), path({'testdata'}, tuple('x')))
      assert.equal(path('testdata/x'), path(tuple('testdata'), {'x'}))
      assert.equal(path('testdata/x'), path(tuple({'testdata', 'x'})))
      assert.equal(path('testdata/x'), path(tuple({tuple('testdata', 'x')})))
    end)
    it("2 + .. = 1", function()
      assert.equal('testdata', tostring(path('testdata', 'x', '..')))
      assert.equal(path('testdata'), path('testdata', 'x', '..'))
      assert.equal(path('testdata'), path('./testdata', 'x', '..'))
      assert.equal(path('testdata'), path({'testdata', 'x', '..'}))
      assert.equal(path('testdata'), path({'testdata', 'x'}, '..'))
      assert.equal(path('testdata'), path({'testdata'}, 'x', '..'))
      assert.equal(path('testdata'), path({'testdata'}, {'x'}, {'..'}))
      assert.equal(path('testdata'), path({'testdata'}, 'x', {'..'}))
      assert.equal(path('testdata'), path({'testdata'}, {'x'}, '..'))
      assert.equal(path('testdata'), path('testdata', {'x'}, {'..'}))

      assert.equal(path('testdata'), path(tuple({'testdata'}, {'x'}, {'..'})))
      assert.equal(path('testdata'), path(tuple({'testdata'}, {tuple('x')}, tuple({'..'}))))

      assert.equal('testdata', tostring(path('testdata', 'x', '..')))
      assert.equal(path('testdata'), path(path('testdata'), 'x', '..'))
      assert.equal(path('testdata'), path(path('./testdata'), 'x', '..'))
      assert.equal(path('testdata'), path(path({'testdata', 'x', '..'})))
      assert.equal(path('testdata'), path(path({'testdata', 'x'}), '..'))
      assert.equal(path('testdata'), path(path({'testdata'}), 'x', '..'))
      assert.equal(path('testdata'), path(path({'testdata'}), {'x'}, {'..'}))
      assert.equal(path('testdata'), path(path({'testdata'}), 'x', {'..'}))
      assert.equal(path('testdata'), path(path({'testdata'}), {'x'}, '..'))
      assert.equal(path('testdata'), path(path('testdata'), {'x'}, {'..'}))
    end)
    it("3 + .. + .. = 1", function()
      assert.equal('testdata', tostring(path('testdata', 'x', '..', 'y', '..')))
      assert.equal(path('testdata'), path('testdata', 'x', '..', 'y', '..'))
      assert.equal(path('testdata'), path('./testdata', 'x', '..', 'y', '..'))
      assert.equal(path('testdata'), path({'testdata', 'x', '..', 'y', '..'}))

      assert.equal(path('testdata'), path(tuple('testdata', 'x', '..', 'y', '..')))
      assert.equal(path('testdata'), path(tuple({'testdata', 'x', '..', 'y', '..'})))
      assert.equal(path('testdata'), path({tuple('testdata', 'x', '..', 'y', '..')}))

      assert.equal(path('testdata'), path({'testdata', tuple('x', '..'), tuple('y', '..')}))
    end)
    it("3 + .. + .. = 1", function()
      assert.equal('testdata', tostring(path(tuple('testdata'), 'x', '..')))
      assert.equal(path('testdata'), path(path('testdata'), 'x', '..'))
      assert.equal(path('testdata'), path(path('./testdata'), 'x', '..'))
      assert.equal(path('testdata'), path(path({'testdata', 'x', '..'})))
      assert.equal(path('testdata'), path(path({'testdata', 'x'}), '..'))
      assert.equal(path('testdata'), path(path({'testdata'}), 'x', '..'))
      assert.equal(path('testdata'), path(path({'testdata'}), {'x'}, {'..'}))
      assert.equal(path('testdata'), path(path({'testdata'}), 'x', {'..'}))
      assert.equal(path('testdata'), path(path({'testdata'}), {'x'}, '..'))
      assert.equal(path('testdata'), path(path('testdata'), {'x'}, {'..'}))
    end)
    it("root", function()
      assert.equal('/testdata', tostring(path('//testdata')))
      assert.equal('/testdata', tostring(path('//testdata')))
      assert.equal('/testdata', tostring(path('/testdata')))
      assert.equal('/testdata', tostring(path('/', 'testdata')))
      assert.equal('/', tostring(path('/', '')))
      assert.equal('/', tostring(path('', '/')))
      assert.equal('/', tostring(path('/', '/')))
      assert.equal(path('/'), path('/'))
      assert.equal(path('/'), path('/', '', '/'))
      assert.equal(path('/testdata/x'), path('/', 'testdata', 'x'))
      assert.equal(path('/testdata/x'), path('/testdata', 'x'))
      assert.equal(path('/testdata/x'), path('/testdata/x'))
    end)
  end)
  it("normalize", function()
    assert.equal(path('testdata/x'), path('testdata/x/'))
    assert.equal(path('testdata/x'), path('testdata/x'))
    assert.equal(path('testdata/x'), path('testdata//x'))
    assert.equal(path('testdata/x'), path('testdata///x'))
    assert.equal(path('testdata/x'), path('testdata////x'))

    assert.equal(path('testdata/x'), path('testdata/x/'))
    assert.equal(path('testdata/x'), path('testdata//x//'))
    assert.equal(path('testdata/x'), path('testdata///x///'))
    assert.equal(path('testdata/x'), path('testdata////x///'))
    assert.equal(path('testdata/x'), path('testdata', 'x//'))

    assert.equal(path('testdata/x'), path('testdata/x/../y/z/c/../../../x'))
    assert.equal(path('testdata/x'), path('testdata/../testdata/../testdata/x'))
    assert.equal(path('testdata/x'), path('testdata///x'))
    assert.equal(path('testdata/x'), path('testdata////x'))
  end)
  describe("isdir/isfile/exists", function()
    it("regular", function()
      assert.is_true(path('testdata').exists)
      assert.is_true(path('testdata/test').exists)
      assert.is_true(path('testdata/dir').exists)

      assert.is_true(path('testdata/dir').isdir)
      assert.is_nil(path('testdata/dir').isfile)
      assert.is_nil(path('testdata/dir').islink)

      assert.is_true(path('testdata/test').isfile)
      assert.is_nil(path('testdata/test').isdir)
      assert.is_nil(path('testdata/test').islink)

      assert.is_nil(path('testdata/noneexistent').exists)
      assert.is_nil(path('testdata/noneexistent').isdir)
      assert.is_nil(path('testdata/noneexistent').isfile)
      assert.is_nil(path('testdata/noneexistent').islink)
    end)
    it("symlink file", function()
      assert.is_true(path('testdata/link/file').islink)

      assert.equal('testdata/link/file', tostring(path('testdata/link/file')))
      assert.equal('file', path('testdata/link/file')[-1])
      assert.is_number(path('testdata/link/file').size)

      assert.is_true(path('testdata/link/file').islink)
      assert.is_true(path('testdata/link/file').exists)
      assert.equal('testdata/test', tostring(path('testdata/link/file').target))
      assert.equal(path('testdata', 'test'), path('testdata/link/file').target)

      assert.is_nil(path('testdata/link/file').badlink)
    end)
    it("symlink dir", function()
      assert.is_true(path('testdata/link/dir').islink)
      assert.is_true(path('testdata/link/dir').exists)
      assert.is_true(path('testdata/link/dir').target.isdir)
      assert.equal(path('testdata', 'dir'), path('testdata/link/dir').target)
      assert.is_nil(path('testdata/link/dir').badlink)
      assert.is_number(path('testdata/link/dir').size)
    end)
    it("symlink noneexistent", function()
      assert.is_true(path('testdata/link/noneexistent').islink)
      assert.is_true(path('testdata/link/noneexistent').exists)
      assert.is_nil(path('testdata/link/noneexistent').isfile)
      assert.is_nil(path('testdata/link/noneexistent').isdir)

      assert.is_true(path('testdata/link/noneexistent').badlink)
      assert.is_true(path('testdata/link/noneexistent').badlink)
      assert.is_nil(path('testdata/link/noneexistent').size)
    end)
  end)
  it("index", function()
    assert.equal('test_symlink', path('testdata/test_symlink')[-1])
    assert.same({'testdata','test_symlink'}, path('testdata/test_symlink')[{}])
  end)
  it("root/isabs/abs", function()
    assert.is_nil(path('').isabs)
    assert.is_nil(path('testdata').isabs)
    assert.is_nil(path('lua/meta/is').isabs)

    assert.equal(1, #path('/usr'))
    assert.equal('', path('/usr')[-2])
    assert.is_true(path('/usr').isabs)

    assert.equal('/usr/bin', tostring(path('/', 'usr', 'bin').abs))
  end)
--[[
  it("root/isabs/abs/ext", function()
    assert.is_nil(path('').root)
    assert.is_nil(path('').isabs)

    assert.equal('/', path('/usr').root)
    assert.is_true(path('/usr').isabs)

    assert.equal('txt', (path('testdata', 'mkdir') .. 'file.txt').ext)
    assert.equal('zip', (path('testdata', 'mkdir') .. 'file.xls.zip').ext)

    assert.equal('/usr/bin', tostring(path('/', 'usr', 'bin').abs))

    local paths = require 'paths'
    assert.equal(paths.concat('testdata', 'ok'), tostring(path('testdata/ok').abs))

    assert.equal('\\', path('\\Device').root)
    assert.is_true(path('\\Device').isabs)
  end)
  it("unc", function()
    local sep = "\\"
    assert.equal("\\\\", sep..sep)

    assert.equal("\\\\server\\share", path('\\\\server\\share').netunc)
    assert.equal("\\\\server\\share", path('\\\\server\\share\\').netunc)

    assert.equal('\\\\server\\with space', path('"\\\\server\\with space"').netunc)
    assert.equal('\\\\server\\with space', path('"\\\\server\\with space"\\').netunc)
    assert.equal('\\\\server\\spacepast', path('"\\\\server\\spacepast\\some\\a space x"\\').netunc)

    assert.equal('\\Device', path('\\Device').sysunc)
    assert.equal('\\Device', path('\\Device\\').sysunc)
    assert.equal('\\Device', path('\\Device\\HarddiskVolume2').sysunc)
    assert.equal('\\Device', path('\\Device\\HarddiskVolume2\\').sysunc)

    assert.equal("\\\\?\\Volume{4c1b02c4-d990-11dc-99ae-806e6f6e6963}", path('\\\\?\\Volume{4c1b02c4-d990-11dc-99ae-806e6f6e6963}').sysunc)
    assert.equal("\\\\?\\Volume{4c1b02c4-d990-11dc-99ae-806e6f6e6963}", path('\\\\?\\Volume{4c1b02c4-d990-11dc-99ae-806e6f6e6963}\\').sysunc)
  end)
--]]
end)