describe("is.alike", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = require "meta.is"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.alike)
    assert.truthy(is.callable(is.alike))
  end)
  it("positive", function()
    assert.is_true(is.alike({},{}))
    assert.is_true(is.alike(meta.seen({}), meta.seen({})))
    assert.is_true(is.alike(meta, require 'meta.loader'))
    assert.is_true(is.alike(0, 0))
    assert.is_true(is.alike(1, 1))
    assert.is_true(is.alike(true, true))
    assert.is_true(is.alike(false, false))
    assert.is_true(is.alike('',''))
    assert.is_true(is.alike('a','a'))
    assert.is_true(is.alike({},{1}))
    assert.is_true(is.alike(table(),table()))
    assert.is_true(is.alike(string.lower,string.lower))
  end)
  it("negative", function()
    assert.is_nil(is.alike({}, table()))
    assert.is_nil(is.alike(1, 0))
    assert.is_nil(is.alike(true, false))
    assert.is_nil(is.alike('','a'))
    assert.is_nil(is.alike('a','b'))
    assert.is_nil(is.alike(table(),string.lower))
    assert.is_nil(is.alike(string.lower,string.upper))
  end)
  it("nil", function()
    assert.is_nil(is.alike(nil, nil))
    assert.is_nil(is.alike(nil))
    assert.is_nil(is.alike())
  end)
end)