describe("is.atom", function()
	local is, non
	setup(function()
    require "meta"
    is = require "meta.is"
    non = is.non
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.atom)
    assert.truthy(is.callable(is.atom))
  end)
  it("positive", function()
    assert.is_true(is.atom(1))
    assert.is_true(is.atom(true))
    assert.is_true(is.atom('some'))
    assert.is_true(is.atom(nil))
  end)
  it("negative", function()
    assert.is_nil(is.atom({}))
    assert.is_nil(is.atom(string.lower))
  end)
  it("nil", function()
    assert.is_true(is.atom(nil))
    assert.is_true(is.atom())
  end)
  it("non", function()
    assert.equal(true, rawget(non, '__non'))
    assert.equal(true, rawget(non.atom, '__non'))
    assert.is_nil(non.atom(nil))
    assert.is_nil(non.atom())
    assert.is_true(non.atom({}))
    assert.is_true(non.atom(string.lower))
    assert.is_nil(non.atom(1))
    assert.is_nil(non.atom(true))
    assert.is_nil(non.atom('some'))
    assert.is_nil(non.atom(nil))
  end)
end)