describe("is.atom", function()
	local is
	setup(function()
    require "meta"
    is = require "meta.is"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.atom)
    assert.truthy(is.callable(is.atom))
  end)
  it("positive", function()
    assert.is_true(is.atom(1))
    assert.is_true(is.atom(true))
    assert.is_true(is.atom('some'))
    assert.is_true(is.atom(nil))
  end)
  it("negative", function()
    assert.is_nil(is.atom({}))
    assert.is_nil(is.atom(string.lower))
  end)
  it("nil", function()
    assert.is_true(is.atom(nil))
    assert.is_true(is.atom())
  end)
end)