describe("is.cache", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = require "meta.is"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.cache)
    assert.truthy(is.callable(is.cache))
  end)
  it("positive", function()
    assert.is_true(is.cache(meta.cache.type))
    assert.is_true(is.cache('type'))
  end)
  it("negative", function()
    assert.is_nil(is.cache({}))
    assert.is_nil(is.cache(0))
    assert.is_nil(is.cache(''))
    assert.is_nil(is.cache(false))
    assert.is_nil(is.cache(true))
  end)
  it("nil", function()
    assert.is_nil(is.cache(nil, nil))
    assert.is_nil(is.cache(nil))
    assert.is_nil(is.cache())
  end)
end)
