describe("is.coroutine", function()
	local meta, is, call
	setup(function()
    meta = require "meta"
    is = meta.is
    call = meta.call
	end)
  it("meta", function()
    assert.callable(is.coroutine)
  end)
  it("positive", function()
    assert.is_true(is.coroutine(coroutine.create(function() return 'meta' end)))
    assert.is_true(is.coroutine(call.create(function() return 'meta' end)))
    assert.is_true(is.coroutine(call.wrap(function() return 'meta' end)))
  end)
  it("negative", function()
    assert.is_nil(is.coroutine({}))
    assert.is_nil(is.coroutine(setmetatable({},{})))
    assert.is_nil(is.coroutine(string.upper))
    assert.is_nil(is.coroutine(0))
    assert.is_nil(is.coroutine(''))
    assert.is_nil(is.coroutine(false))
    assert.is_nil(is.coroutine(true))
  end)
  it("nil", function()
    assert.is_nil(is.coroutine(nil, nil))
    assert.is_nil(is.coroutine(nil))
    assert.is_nil(is.coroutine())
  end)
end)
