describe("is.dir", function()
  local meta, is
  setup(function()
    meta = require "meta"
    is = meta.is
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable)
    assert.truthy(is.callable(is.dir))
  end)
  describe("tests", function()
    it("cwd", function()
      assert.is_true(is.dir(''))
      assert.is_true(is.dir('.'))
    end)
    it("dir", function()
      assert.is_true(is.dir('testdata'))
      assert.is_true(is.dir('testdata/ok'))
      assert.is_true(is.dir('/'))
      assert.is_true(is.dir('/tmp'))
      assert.is_true(is.dir('/var'))
      assert.is_true(is.dir('testdata/loader/noinit'))
      assert.is_nil(is.dir('testdata/loader/failed'))
    end)
    it("file", function() assert.is_nil(is.dir('testdata/test')) end)
    it("file.empty", function() assert.is_nil(is.dir('testdata/empty')) end)
    it("noneexistent", function() assert.is_nil(is.dir('testdata/noneexistent')) end)
    it("dev_zero", function() assert.is_nil(is.dir('/dev/zero')) end)
    it("dev_zero", function() assert.is_nil(is.dir('/dev/null')) end)
  end)
end)