describe("is.factory", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = meta.is
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.factory)
    assert.truthy(is.callable(is.factory))
  end)
  it("positive", function()
    assert.is_true(is.factory(meta))
    assert.is_true(is.factory(meta.is))
    assert.is_true(is.toindex(meta.seen))
    assert.is_true(is.factory(meta.seen))
    assert.is_true(is.factory(meta.wrapper))
  end)
  it("negative", function()
    assert.is_nil(is.factory(false))
    assert.is_nil(is.factory(string.upper))
  end)
  it("nil", function()
    assert.is_nil(is.factory(nil))
    assert.is_nil(is.factory())
  end)
end)
