describe("is.file", function()
  local meta, is
  setup(function()
    meta = require "meta"
    is = meta.is
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable)
    assert.truthy(is.callable(is.file))
  end)
  describe("tests", function()
    it("cwd", function()
      assert.is_nil(is.file(''))
      assert.is_nil(is.file('.'))
    end)
    it("dir", function()
      assert.is_nil(is.file('testdata'), 'testdata')
      assert.is_nil(is.file('testdata/ok'), 'testdata/ok')
      assert.is_nil(is.file('/'), '/')
      assert.is_nil(is.file('/tmp'), '/tmp')
      assert.is_nil(is.file('/var'), '/var')
      assert.is_nil(is.file('testdata/loader/noinit'), 'testdata/loader/noinit')
      assert.is_nil(is.file('testdata/loader/failed'), 'testdata/loader/failed')
    end)
    it("file", function() assert.is_true(is.file('testdata/test')) end)
    it("file.empty", function() assert.is_true(is.file('testdata/empty')) end)
    it("noneexistent", function() assert.is_nil(is.file('testdata/noneexistent')) end)
    it("dev_zero", function() assert.is_true(is.file('/dev/zero')) end)
    it("dev_zero", function() assert.is_true(is.file('/dev/null')) end)
  end)
end)