describe("is.indexable", function()
	local is
	setup(function()
    is = require "meta.is"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.indexable)
    assert.truthy(is.callable(is.indexable))
    assert.is_table(is.mt)
    assert.equal(is.indexable, is.mt.__index)
  end)
  it("positive", function()
    assert.is_true(is.indexable(table))
    assert.is_true(is.indexable(is))
  end)
  it("negative", function()
    assert.is_nil(is.indexable("some"))
    assert.is_nil(is.indexable(true))
    assert.is_nil(is.indexable({7}))
    assert.is_nil(is.indexable(1))
    assert.is_nil(is.indexable("1"))
    assert.is_nil(is.indexable(table.remove))
  end)
  it("nil", function()
    assert.is_nil(is.indexable(nil))
    assert.is_nil(is.indexable())
  end)
end)