describe("is.instance", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = meta.is
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.instance)
    assert.truthy(is.callable(is.instance))
  end)
  it("positive", function()
    assert.is_true(is.instance(meta))
    assert.is_true(is.instance(meta.is))
    assert.is_true(is.toindex(meta.seen))
    assert.is_true(is.instance(meta.seen))
    assert.is_true(is.instance(meta.wrapper))
  end)
  it("negative", function()
    assert.is_nil(is.instance(false))
    assert.is_nil(is.instance(string.upper))
  end)
  it("nil", function()
    assert.is_nil(is.instance(nil))
    assert.is_nil(is.instance())
  end)
end)
