describe("is.loader", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = require "meta.is"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.loader)
    assert.truthy(is.callable(is.loader))
    assert.equal(meta.loader, meta.cache.new.loader)
  end)
  it("positive", function()
    assert.is_true(is.loader(meta.loader('meta')))
    assert.is_true(is.loader(meta))
  end)
  it("negative", function()
    assert.is_nil(is.loader(meta.module('meta')))
    assert.is_nil(is.loader({}))
    assert.is_nil(is.loader(setmetatable({},{})))
    assert.is_nil(is.loader(string.upper))
    assert.is_nil(is.loader(0))
    assert.is_nil(is.loader(''))
    assert.is_nil(is.loader(false))
    assert.is_nil(is.loader(true))
  end)
  it("nil", function()
    assert.is_nil(is.loader(nil, nil))
    assert.is_nil(is.loader(nil))
    assert.is_nil(is.loader())
  end)
end)
