describe("is.module", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = require "meta.is"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.module)
    assert.truthy(is.callable(is.module))
  end)
  it("positive", function()
    assert.is_true(is.module(meta.module('meta.module')))
    assert.is_true(is.module(meta.module('meta.loader')))
    assert.is_true(is.module(meta.module('meta')))
    assert.is_true(is.module(meta))
    assert.is_true(is.module(meta.loader('meta.is')))
  end)
  it("negative", function()
    assert.is_nil(is.module({}))
    assert.is_nil(is.module(0))
    assert.is_nil(is.module(''))
    assert.is_nil(is.module(false))
    assert.is_nil(is.module(true))
  end)
  it("nil", function()
    assert.is_nil(is.module(nil, nil))
    assert.is_nil(is.module(nil))
    assert.is_nil(is.module())
  end)
end)
