describe("is.null", function()
	local is, non
	setup(function()
    require "meta"
    is = require "meta.is"
    non = is.non
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.null)
    assert.truthy(is.callable(is.null))
  end)
  it("positive", function()
    assert.is_true(is.null(nil))
  end)
  it("negative", function()
    assert.is_nil(is.null({}))
    assert.is_nil(is.null(string.lower))
    assert.is_nil(is.null(1))
    assert.is_nil(is.null(true))
    assert.is_nil(is.null(false))
    assert.is_nil(is.null('some'))
    assert.is_nil(is.null(''))
  end)
  it("nil", function()
    assert.is_true(is.null(nil))
    assert.is_true(is.null())
  end)
  it("non", function()
    assert.equal(true, rawget(non, '__non'))
    assert.equal(true, rawget(non.null, '__non'))
    assert.is_nil(non.null(nil))
    assert.is_nil(non.null())
    assert.is_true(non.null({}))
    assert.is_true(non.null(string.lower))
    assert.is_true(non.null(1))
    assert.is_true(non.null(true))
    assert.is_true(non.null('some'))
  end)
end)