describe("is.pkgloaded", function()
	local is
	setup(function()
    require "meta"
    is = require "meta.is"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.pkgloaded)
    assert.truthy(is.callable(is.pkgloaded))
  end)
  it("positive", function()
    assert.is_true(is.pkgloaded('meta.is'))
    assert.is_true(is.pkgloaded('meta'))
  end)
  it("negative", function()
    assert.is_nil(is.pkgloaded('meta.isis'))
    assert.is_nil(is.pkgloaded('meta.noneexistent'))

    assert.is_nil(is.pkgloaded({}))
    assert.is_nil(is.pkgloaded(0))
    assert.is_nil(is.pkgloaded(''))
    assert.is_nil(is.pkgloaded(false))
    assert.is_nil(is.pkgloaded(true))
  end)
  it("nil", function()
    assert.is_nil(is.pkgloaded(nil, nil))
    assert.is_nil(is.pkgloaded(nil))
    assert.is_nil(is.pkgloaded())
  end)
end)