describe("is.similar", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = require "meta.is"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.similar)
    assert.truthy(is.callable(is.similar))
  end)
  it("positive", function()
    assert.is_true(is.similar({},{}))
    assert.is_true(is.similar(meta.seen({}), meta.seen({})))
    assert.is_true(is.similar(meta, meta.loader))
    assert.is_true(is.similar(0, 0))
    assert.is_true(is.similar(1, 1))
    assert.is_true(is.similar(true, true))
    assert.is_true(is.similar(false, false))
    assert.is_true(is.similar('',''))
    assert.is_true(is.similar('a','a'))
    assert.is_true(is.similar({},{1}))
    assert.is_true(is.similar(string.lower,string.lower))
    assert.is_true(is.similar(table(),table()))
    assert.is_true(is.similar(meta.clone(table()),table()))
  end)
  it("negative", function()
    assert.is_nil(is.similar({}, table()))
    assert.is_nil(is.similar(1, 0))
    assert.is_nil(is.similar(true, false))
    assert.is_nil(is.similar('','a'))
    assert.is_nil(is.similar('a','b'))
    assert.is_nil(is.similar(table(),string.lower))
    assert.is_nil(is.similar(string.lower,string.upper))
  end)
  it("nil", function()
    assert.is_nil(is.similar(nil, nil))
    assert.is_nil(is.similar(nil))
    assert.is_nil(is.similar())
  end)
end)
