describe("is.toindex", function()
	local meta, is
	setup(function()
    meta = require "meta"
    is = meta.is
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.toindex)
    assert.truthy(is.callable(is.toindex))
  end)
  it("positive", function()
    assert.is_true(is.toindex({}))
    assert.is_true(is.toindex(meta.seen))
    assert.is_true(is.toindex(table.remove))
  end)
  it("negative", function()
    assert.is_nil(is.toindex("some"))
    assert.is_nil(is.toindex(true))
    assert.is_nil(is.toindex(1))
    assert.is_nil(is.toindex("1"))
  end)
  it("nil", function()
    assert.is_nil(is.toindex(nil))
    assert.is_nil(is.toindex())
  end)
end)