describe("is.wrapper", function()
	local meta, is, wrapper
	setup(function()
    meta = require "meta"
    is = meta.is
    wrapper = require "meta.wrapper"
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.wrapper)
    assert.truthy(is.callable(is.wrapper))
    assert.truthy(is.callable(wrapper))
  end)
  it("positive", function()
    assert.is_true(is.wrapper(wrapper))
    local match = wrapper('meta.matcher', string.matcher)
    assert.truthy(is.callable(match))
    assert.is_true(is.wrapper(match))
  end)
  it("negative", function()
    assert.is_nil(is.wrapper({}))
    assert.is_nil(is.wrapper({'type'}))
    assert.is_nil(is.wrapper(0))
    assert.is_nil(is.wrapper(''))
    assert.is_nil(is.wrapper(false))
    assert.is_nil(is.wrapper(true))
  end)
  it("nil", function()
    assert.is_nil(is.wrapper(nil))
    assert.is_nil(is.wrapper())
  end)
end)