describe("boolean", function()
  local boolean
  setup(function()
    require 'meta'
    boolean = require 'meta.boolean'
  end)
  it("meta", function()
    assert.callable(boolean)
  end)
  it("positive", function()
    assert.is_true(boolean(1))
    assert.is_true(boolean(7))
    assert.is_true(boolean(-1))
    assert.is_true(boolean(-7))
    assert.is_true(boolean('any'))
    assert.is_true(boolean('true'))
    assert.is_true(boolean('TRUE'))
    assert.is_true(boolean(true))
    assert.is_true(boolean({x=1}))
    assert.is_true(boolean({{}}))
  end)
  it("negative", function()
    assert.is_false(boolean(0))
    assert.is_false(boolean(''))
    assert.is_false(boolean(' '))
    assert.is_false(boolean('  '))
    assert.is_false(boolean('	'))
    assert.is_false(boolean('		'))
    assert.is_false(boolean("	\r 	"))
    assert.is_false(boolean("	\n 	"))
    assert.is_false(boolean(false))
    assert.is_false(boolean({}))
    assert.is_false(boolean("false"))
    assert.is_false(boolean("0"))
    assert.is_false(boolean("FALSE"))
  end)
  it("nil", function()
    assert.is_false(boolean(nil))
    assert.is_false(boolean())
  end)
end)