local t = require "test.chain"
describe('chain', function()
  it("var", function()
    assert.is_nil(rawget(t, 'country'))
    assert.is_nil(rawget(t, 'name'))
    assert.is_nil(rawget(t, 'last'))
    assert.equal('US', t.country)
    assert.equal('John', t.name)
    assert.equal('Smith', t.last)
    assert.equal('John', rawget(t, 'name'))
    assert.equal('Smith', rawget(t, 'last'))
  end)
  it("ok", function()
    assert.is_not_nil(t)
    assert.is_not_nil(t.ok)
    assert.equal('ok', t.ok.message.data)
  end)
end)
