describe("is", function()
  local is
  setup(function()
    is = require "meta.is" ^ 'testdata'
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable)
    assert.equal(is, is ^ 'meta')
  end)
  it("index", function()
    assert.equal('is', is[1])
    assert.equal('is', is[-1])
    assert.same({'is'}, is[{}])
  end)
  it("tostring", function()
    assert.equal('is', tostring(is))
    assert.equal('is/has', tostring(is.has))
  end)
  it("path", function()
    local path = string.joiner('/')
    assert.equal('a/b/c', path({'a', 'b'}, 'c'))
    assert.equal('is/has', path(is, 'has'))
  end)
  it("predicates", function()
    assert.truthy(is.callable(is.like))
    assert.truthy(is.callable(is.has.value))

    assert.truthy(is.callable(is.match[false]))
    assert.truthy(is.callable(is.match.space))
    assert.truthy(is.match.space('  '))
  end)
end)