local meta = require "meta"
local isdir = meta.loader.isdir
describe('isdir', function()
  it("dir", function()
    assert.truthy(isdir('test'))
    assert.truthy(isdir('test/ok'))
    assert.truthy(isdir('/'))
    assert.truthy(isdir('/tmp'))
    assert.truthy(isdir('/var'))
    assert.truthy(isdir('test/loader/noinit'))
    assert.falsy(isdir('test/loader/failed'))
  end)
  it("file", function()
    assert.falsy(isdir('test/test'))
  end)
  it("file.empty", function()
    assert.falsy(isdir('test/empty'))
  end)
  it("noneexistent", function()
    assert.is_nil(isdir('noneexistent'))
  end)
  it("dev_zero", function()
    assert.falsy(isdir('/dev/zero'))
  end)
  it("dev_zero", function()
    assert.falsy(isdir('/dev/null'))
  end)
end)
