local testdata = 'testdata'
local isdir = require "meta.isdir"
describe('isdir', function()
  it("dir", function()
    assert.truthy(isdir(testdata .. ''))
    assert.truthy(isdir(testdata .. '/ok'))
    assert.truthy(isdir('/'))
    assert.truthy(isdir('/tmp'))
    assert.truthy(isdir('/var'))
    assert.truthy(isdir(testdata .. '/loader/noinit'))
    assert.falsy(isdir(testdata .. '/loader/failed'))
  end)
  it("value", function()
    assert.equal(testdata .. '', isdir(testdata .. '', true))
    assert.equal(testdata .. '/ok', isdir(testdata .. '/ok', true))
    assert.equal('/tmp', isdir('/tmp', true))
    assert.equal('/var/tmp', isdir('/var/tmp', true))
    assert.equal(testdata .. '/loader/noinit', isdir(testdata .. '/loader/noinit', true))
    assert.is_nil(isdir(testdata .. '/loader/failed', true))
  end)
  it("file", function() assert.falsy(isdir(testdata .. '/test')) end)
  it("file.empty", function() assert.falsy(isdir(testdata .. '/empty')) end)
  it("noneexistent", function() assert.is_nil(isdir(testdata .. '/noneexistent')) end)
  it("dev_zero", function() assert.falsy(isdir('/dev/zero')) end)
  it("dev_zero", function() assert.falsy(isdir('/dev/null')) end)
end)
