local meta = require "meta"
local isdir = meta.loader.isdir
local testdata = 'testdata'
describe('isdir', function()
  it("dir", function()
    assert.truthy(isdir(testdata .. ''))
    assert.truthy(isdir(testdata .. '/ok'))
    assert.truthy(isdir('/'))
    assert.truthy(isdir('/tmp'))
    assert.truthy(isdir('/var'))
    assert.truthy(isdir(testdata .. '/loader/noinit'))
    assert.falsy(isdir(testdata .. '/loader/failed'))
  end)
  it("file", function()
    assert.falsy(isdir(testdata .. '/test'))
  end)
  it("file.empty", function()
    assert.falsy(isdir(testdata .. '/empty'))
  end)
  it("noneexistent", function()
    assert.is_nil(isdir(testdata .. '/noneexistent'))
  end)
  it("dev_zero", function()
    assert.falsy(isdir('/dev/zero'))
  end)
  it("dev_zero", function()
    assert.falsy(isdir('/dev/null'))
  end)
end)
