local testdata = 'testdata'
local tl = require "testdata/loader"
local path = require "meta.path"
describe('loader', function()
  it("ok", function()
    assert.is_table(tl)
    assert.is_not_nil(tl.ok)
    assert.equal('ok', tl.ok.message.data)
  end)
  it("dot", function()
    assert.is_not_nil(tl)
    assert.is_not_nil(tl.dot)
    assert.equal('ok', tl.dot['ok.message'].data)
  end)
  it("path", function()
    assert.equal(testdata .. '/loader', path(testdata, 'loader'))
    assert.equal(testdata .. '/loader', path(testdata .. '/loader'))
    assert.equal(testdata .. '/loader/noinit', path(testdata .. '/loader', 'noinit'))
    assert.equal(testdata .. '/loader/noinit', path(testdata .. '.loader', 'noinit'))
  end)
  it("noinit", function()
    assert.is_not_nil(tl)
    assert.equal('table', type(tl))
    assert.is_not_nil(tl.noinit)
    assert.equal('table', type(tl.noinit))
    assert.equal('ok', tl.noinit['ok.message'].data)
    assert.equal('ok', tl.noinit.message.data)
  end)
  it("failed", function()
    --    assert.has_error(function() return tl.failed end)
    --    assert.has_error(function() local m, err=tl.failed; if not m then error(m) end; return m end)
  end)
end)
