describe("math", function()
  setup(function() require 'meta.math' end)
  it("round", function()
    assert.is_function(math.round)
    assert.equal(1, math.round(1), '1')
    assert.equal(1, math.round(1.3), '1.3')
    assert.equal(1, math.round(0.8), '0.8')
    assert.equal(2, math.round(2), '2')
    assert.equal(2, math.round(1.51), '1.51')
    assert.equal(2, math.round(1.88), '1.88')
    assert.equal(2, math.round(2.4), '2.4')
  end)
  it("max", function()
    assert.equal(1, math.max(1))
    assert.equal(1, math.max(1, 1))
    assert.equal(2, math.max(1, 2))
    assert.equal(3, math.max(1, 2, 3))
    assert.equal(1, math.max(1, -1))
    assert.equal(1, math.max(1, -2))
    assert.equal(3, math.max(1, -2, 3))
    assert.equal(1, math.max(-1, 1))
    assert.equal(2, math.max(-1, 2))
    assert.equal(3, math.max(-1, -2, 3))
  end)
end)