describe('methods', function()
  local mm, oo
  setup(function()
    require "compat53"
    mm = require "meta.methods"
    oo = setmetatable({}, {__call = function(self, ...) end, __div = function(self, ...) end, test = function(self, ...) end})
  end)
  it("validity", function()
    assert.is_function(mm)
  end)
  it("nil", function()
    assert.is_nil(mm())
    assert.is_nil(mm(nil))
    assert.is_nil(mm(nil, nil))
    assert.is_nil(mm(nil, {}))
  end)
  it("__metamethods", function()
    local r = mm(oo)
    assert.is_table(r)
    assert.is_function(r.__call)
    assert.is_nil(r.__index)
    assert.is_function(r.__div)
    assert.is_nil(r.test)
    local o = getmetatable(oo)
    assert.equal(o.__call, r.__call)
    assert.equal(o.__div, r.__div)
    assert.not_equal(o.test, r.test)
  end)
  it("__metamethods + __index", function()
    local r = mm(oo, {__index = function() end})
    assert.is_table(r)
    assert.is_function(r.__call)
    assert.is_function(r.__index)
    assert.is_function(r.__div)
    assert.is_nil(r.test)
    local o = getmetatable(oo)
    assert.equal(o.__call, r.__call)
    assert.equal(o.__div, r.__div)
    assert.not_equal(o.test, r.test)
    assert.not_equal(o.__index, r.__index)
  end)
end)
