describe('prequire', function()
  local testdata, meta
  setup(function()
    require "compat53"
    testdata = 'testdata'
    meta = require "meta"
  end)
  it("ok", function()
    local t, err = meta.prequire(testdata .. ".ok")
    assert.is_table(t)
    assert.is_nil(err)
    assert.equal('ok', t.message.data)
  end)
  it("noneexistent", function()
    local ff = function() return assert(meta.prequire(testdata .. ".noneexistent")) end
    assert.has_error(ff)
  end)
  it("failed", function()
    local o, err = meta.prequire(testdata .. ".failed", true)
    assert.is_nil(o)
    assert.is_not_nil(err)
  end)
  it("or", function()
    assert.truthy(meta.prequire("noneexistent") or meta.prequire(testdata .. ".ok"))
    assert.truthy(meta.prequire(testdata .. ".ok") or meta.prequire("noneexistent"))
    assert.truthy(meta.prequire("noneexistent") or meta.prequire("os"))
    assert.truthy(meta.prequire("os") or meta.prequire("noneexistent"))
    assert.truthy((meta.prequire("noneexistent") or meta.prequire("os")).remove)
  end)
  it("sub", function()
    local prequire = meta.prequire("meta.")
    assert.is_function(prequire)
    assert.equal(meta.prequire("meta.loader"), prequire(".loader"))
  end)
end)
