local testdata = 'testdata'
local prequire = require "meta.prequire"
describe('prequire', function()
  it("ok", function()
    local t, err = prequire(testdata .. ".ok")
    assert.is_table(t)
    assert.is_nil(err)
    assert.equal('ok', t.message.data)
  end)
  it("noneexistent", function()
    local ff = function() return assert(prequire(testdata .. ".noneexistent")) end
    assert.has_error(ff)
  end)
  it("failed", function()
    local t, err = prequire(testdata .. ".failed")
    assert.is_nil(t)
    assert.is_not_nil(err)
  end)
  it("or", function()
    assert.truthy(prequire("noneexistent") or prequire(testdata .. ".ok"))
    assert.truthy(prequire(testdata .. ".ok") or prequire("noneexistent"))
    assert.truthy(prequire("noneexistent") or prequire("os"))
    assert.truthy(prequire("os") or prequire("noneexistent"))
    assert.truthy((prequire("noneexistent") or prequire("os")).remove)
  end)
end)
