describe('require', function()
  local testdata, require = nil, require
  setup(function()
    require "compat53"
    testdata = 'testdata'
    require = require "meta.require"(testdata)
  end)
  it("ok", function()
    local t, err = require ".ok"
    assert.is_table(t)
    assert.is_nil(err)
    assert.equal('ok', t.message.data)
  end)
  it("noneexistent", function()
    assert.has_error(function() return require(".noneexistent") end)
    assert.has_error(function() return require("noneexistent") end)
  end)
  it("failed", function()
    assert.has_error(function() return require(".failed") end)
  end)
  it("or", function()
    assert.truthy(require("noneexistent", false) or require(".ok"))
    assert.truthy(require(".ok") or require("noneexistent", false))
    assert.truthy(require("noneexistent", false) or require("os"))
    assert.truthy(require("os") or require("noneexistent", false))
    assert.truthy((require("noneexistent", false) or require("os")).remove)
  end)
end)
