describe("set", function()
  local meta, set
  setup(function()
    meta = require "meta"
    set = meta.set
  end)
  it("__add + __sub", function()
    assert.same(set('b') + 'c', set('a', 'b', 'c')-'a')
  end)
  it("create", function()
    assert.is_table(set())
    assert.is_table(set({}))
    assert.same(set(), set({}))
    assert.equal('a', set('a')['a'])
    assert.is_table(set('a', 'b'))
  end)
  it("of", function()
--    local nums = set:of(tonumber)
--    assert.is_table(nums)
    local nums = set ^ tonumber
    assert.is_table(nums)
    assert.equal(nums(1, 7, 88, 1), nums('1', '7', '88'))
  end)
  it("compare", function()
    assert.is_true(set('a', 'b', 'c') <= set('a', 'b', 'c', 'd'))
    assert.is_true(set('a', 'd', 'b', 'c') <= set('a', 'b', 'c', 'd'))
    assert.is_true(set('a', 'd', 'b', 'c') == set('a', 'b', 'c', 'd'))
  end)
end)
