describe("type", function()
  local meta, tt
  setup(function()
    meta = require "meta"
    tt = require 'meta.type'
  end)
  it("positive", function()
    assert.equal('mcache', tt(meta.mcache))
    assert.equal('loader', tt(meta.loader))
    assert.equal('module', tt(meta.module))
  end)
  it("loader", function()
    assert.equal('loader', tt(meta.loader))
    assert.equal('loader', tt(meta))
    assert.equal('module', tt(meta.module))
    assert.equal('is', tt(meta.is))
    assert.equal('mcache', tt(meta.mcache))
    assert.equal('seen', tt(meta.seen))
    assert.equal('call', tt(meta.call))
    assert.equal('type', tt(meta.type))
  end)
  it("require .", function()
    assert.equal('loader', tt(require('meta')))
    assert.equal('loader', tt(require('meta.loader')))
    assert.equal('module', tt(require('meta.module')))
    assert.equal('is', tt(require('meta.is')))
    assert.equal('mcache', tt(require('meta.mcache')))
    assert.equal('seen', tt(require('meta.seen')))
    assert.equal('call', tt(require('meta.call')))
    assert.equal('type', tt(require('meta.type')))
  end)
  it("require /", function()
    assert.equal('loader', tt(require('meta')))
    assert.equal('loader', tt(require('meta/loader')))
    assert.equal('module', tt(require('meta/module')))
    assert.equal('is', tt(require('meta/is')))
    assert.equal('mcache', tt(require('meta/mcache')))
    assert.equal('seen', tt(require('meta/seen')))
    assert.equal('type', tt(require('meta/type')))
    assert.equal('call', tt(require('meta/call')))
  end)
  it("func addr", function()
    local a = string.lower
    local b = string.lower
    assert.equal(tostring(a), tostring(b))
    assert.equal(require('meta.type'), require('meta/type'))
  end)
end)