describe("mcache.root.meta", function()
	local meta, is, mcache
	setup(function()
    meta = require "meta"
    is = meta.is
    mcache = meta.mcache
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(mcache.root))
    assert.equal(true, mcache.conf.root.ordered)
  end)
  it("positive", function()
    assert.equal('meta', mcache.root['meta'])
    assert.equal('meta', mcache.root['meta.loader'])
    assert.equal('meta', mcache.root['meta/loader'])
    assert.equal('meta', mcache.root[1])
    assert.equal('meta', mcache.root['meta/a/b/c/d/e/f/g/h'])

    assert.equal(is, mcache.root('is'))
    assert.equal(mcache, mcache.root('mcache'))
    assert.equal('c', mcache.root('files/i/c/c').x)
  end)
  it("negative", function()
    assert.is_nil(mcache.root[is])
    assert.is_nil(mcache.root.is)
    assert.is_nil(mcache.root[''])
    assert.is_nil(mcache.root[{}])
    assert.is_nil(mcache.root[0])
    assert.is_nil(mcache.root[false])
    assert.is_nil(mcache.root[true])
  end)
  it("nil", function()
    assert.is_nil(mcache.root[nil])
  end)
end)