describe("no.strip", function()
	local meta, is, no
	setup(function()
    meta = require "meta"
    is = meta.is
    no = meta.no
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(no.strip))
  end)
  it("positive", function()
    assert.equal('meta', no.strip('meta'))
    assert.equal('meta', no.strip('meta/init.lua'))
    assert.equal('meta.loader', no.strip('meta.loader/init.lua'))
    assert.equal('meta.loader', no.strip('meta.loader/init.lua'))
    assert.equal('meta/loader', no.strip('meta/loader.lua'))
  end)
  it("negative", function()
    assert.is_nil(no.strip(nil, 'ok'))
    assert.is_nil(no.strip('init.lua'))
    assert.is_nil(no.strip(nil, {}, nil))
    assert.is_nil(no.strip(nil, {}, 'a'))
    assert.is_nil(no.strip(nil, {a=888}, 'a'))
    assert.is_nil(no.strip(''))
    assert.is_nil(no.strip({}))
    assert.is_nil(no.strip(0))
    assert.is_nil(no.strip(1))
    assert.is_nil(no.strip(false))
    assert.is_nil(no.strip(true))
  end)
  it("nil", function()
    assert.is_nil(no.strip())
    assert.is_nil(no.strip(nil))
    assert.is_nil(no.strip(nil, nil))
    assert.is_nil(no.strip(nil, nil, nil))
  end)
end)