describe("call.lift", function()
  local call, lift
  setup(function()
    call = require 'meta.call'
    lift = call.lift
  end)
  it("tostring + tonumber", function()
    local f = lift(tostring, tonumber)
    assert.equal(777, f(777))
    assert.equal(777, f('777'))
  end)
  it("tostring + string.toupper", function()
    local f = lift(tostring, string.upper)
    assert.equal('NEWTON CLASS', f('newton class'))
    assert.equal('MICRO SOFT', f('micro soft'))
  end)
  it("tonumber", function()
    local f = lift(tonumber)
    assert.equal(777, f(777))
    assert.equal(777, f('777'))
  end)
  it("nil", function()
    local f = lift(nil, nil)
    assert.equal('russia', f('russia'))
  end)
end)