describe("module.require", function()
	local req
	setup(function()
    req = require 'meta.module.require'
	end)
  it("meta", function()
    assert.is_function(req)
  end)
  it("positive", function()
    assert.is_function(req('meta.gmt'))
    assert.equal(require('meta.gmt'), req('meta.gmt'))

    assert.is_nil(package.loaded['testdata.ok'])
    assert.not_nil(req('testdata.ok'))
    assert.is_nil(package.loaded['testdata.ok'])

    assert.not_equal(req('testdata.ok'), require('testdata.ok'))
    assert.equal(require('testdata.ok'), req('testdata.ok'))
  end)
  it("negative", function()
    assert.is_nil(req(''))
    assert.is_nil(req('testdata.noneexistent'))
    assert.is_nil(req({}))
    assert.is_nil(req({'type'}))
    assert.is_nil(req(0))
    assert.is_nil(req(false))
    assert.is_nil(req(true))
  end)
  it("nil", function()
    assert.is_nil(req(nil))
    assert.is_nil(req())
  end)
end)