describe("module.rev", function()
	local rev
	setup(function()
    require 'meta'
    rev = require 'meta.module.rev'
	end)
  it("positive", function()
    assert.equal('meta', rev('meta'))
    assert.equal('meta.iter', rev('meta.iter'))
    assert.equal('meta.iter', rev('meta/iter'))
    assert.equal('meta.module', rev('meta.module'))
    assert.equal('meta.module', rev('meta/module'))
  end)
  it("negative", function()
    assert.is_nil(rev(''))
    assert.is_nil(rev({}))
    assert.is_nil(rev({'type'}))
    assert.is_nil(rev(0))
    assert.is_nil(rev(false))
    assert.is_nil(rev(true))
  end)
  it("nil", function()
    assert.is_nil(rev(nil, nil))
    assert.is_nil(rev(nil))
    assert.is_nil(rev())
  end)
end)