describe("module.sub", function()
	local sub
	setup(function()
    require 'meta'
    sub = require 'meta.module.sub'
	end)
  it("positive", function()
    assert.ends('t', sub('t'))
    assert.ends('t/some', sub('t.some'))
    assert.ends('t/some', sub('t/some'))
    assert.ends('t/some', sub('t', 'some'))
    assert.ends('t/any/some', sub('t.any', 'some'))
    assert.ends('t/any/some', sub('t/any', 'some'))
    assert.ends('t/any/some.com', sub('t.any', 'some.com'))
    assert.ends('t/any/some.com', sub('t/any', 'some.com'))
    assert.ends('testdata/init1/file', sub('testdata/init1/file'))
    assert.ends('testdata/init1/file', sub('testdata.init1.file'))
    assert.ends('t/a/b/c/d/e/f/g/h', sub('t', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'))
  end)
  it("negative", function()
    assert.is_nil(sub(''))
    assert.is_nil(sub({}))
    assert.is_nil(sub({'type'}))
    assert.is_nil(sub(0))
    assert.is_nil(sub(false))
    assert.is_nil(sub(true))
  end)
  it("nil", function()
    assert.is_nil(sub(nil, nil))
    assert.is_nil(sub(nil))
    assert.is_nil(sub())
  end)
end)